"""Add Instagram posts and rate limiting tables

Revision ID: e2018a13d044
Revises: 5baf07d919a6
Create Date: 2025-06-14 01:52:54.578258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2018a13d044'
down_revision = '5baf07d919a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instagram_post_id', sa.String(length=100), nullable=False),
    sa.Column('instagram_permalink', sa.Text(), nullable=True),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_instagram_post_id'), 'instagram_posts', ['instagram_post_id'], unique=True)
    op.create_table('instagram_rate_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hour_window', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_request', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hour_window', name='_user_hour_window_uc')
    )
    op.create_index(op.f('ix_instagram_rate_limits_hour_window'), 'instagram_rate_limits', ['hour_window'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_rate_limits_hour_window'), table_name='instagram_rate_limits')
    op.drop_table('instagram_rate_limits')
    op.drop_index(op.f('ix_instagram_posts_instagram_post_id'), table_name='instagram_posts')
    op.drop_table('instagram_posts')
    # ### end Alembic commands ###